### ISSUE TITLE
Add the asdf-community information to the README

### ISSUE THREAD

**Issue by smorimoto** [asdf-vm/asdf-plugins#180]
We've been trying to figure out how to better manage asdf plugins for months. As a result, the asdf-community works relatively well with the help of the community, and it seems like a good idea to mention it in the README. What do you think?

https://github.com/asdf-community/.github

**Comment by Stratus3D** [comment]
@imbsky I'm am fine with that, so long as it is clear that it's not a responsibility of the core team and that plugins made available don't necessarily comply with all of the core teams guidelines for plugins.

**Comment by Stratus3D** [comment]
I'm honestly not a huge fan of the asdf-plugins repository (and the associated `plugin-add` function that pulls from it), simply because it has created additional work for us on the core team. I'm all for having independent indexes/repos of plugins maintained and curated by asdf-users as that will reduce our responsibilities.

**Comment by imbsky** [comment]
Thank you. Yes, I have the exact same opinion. Since I'm both an OCaml programmer and a Void Linux user, I'm going to give some examples related to them, it's definitely better to manage plugins in a way like opam-repository and void-packages. I thoguht it difficult to do in asdf because of the historical problems, so I started a community project, which would be the great if it could be managed in those ways.

**Comment by jthegedus** [comment]
closed in #180
