### ISSUE TITLE
[New Plugin-in] awscli

### ISSUE THREAD

**Issue by shousper** [asdf-vm/asdf-plugins#222]
I'm not sure how possible this might be, but the v2 and v1 processes are quite different, so it might require 2 plugins? 🤷‍♂ Also not sure if it's possible to target specific v2 versions

See:
- https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html
- https://docs.aws.amazon.com/cli/latest/userguide/install-cliv1.html

**Comment by imbsky** [comment]
It should be implementable as a single plugin.

**Comment by MetricMike** [comment]
I've been exploring this plugin and it would vastly simplify support for v1/v2 and arbitrary versions of such if I install from source. That requires relying on:

1) an existing python installation available on the PATH
2) installing or upgrading dependencies to whichever pip is on PATH

In theory, few users would require awscli without already having a usable python installation (whether ASDF- or system-provided). I'm a little more concerned about polluting the pip environment, especially because I'm wary of folks who use project-specific virtualenvs. This is especially a problem if a user installs awscli with one python active on the path, and then switches to another python or virtualenv.

Installing using the "AWS-blessed" packages is a bit tricky because I'm juggling a few different packages that assume a lot for different cases (for example, v1 user linux vs v2 mac in particular have different requirements for sudo and write-access to the installer's preferred location).

While I'm working on that, are there any objections/concerns I should be aware of with this approach?

**Comment by shousper** [comment]
SGTM. I had hoped AWS would make it a little easier to query for a version list, install and update their cli, but that doesn't seem to have changed yet.

FWIW, I gave up pinning and just updated our scripts to work with the then-latest V2 and all was well.

When I raised this it was due to some recent updates that introduced breaking changes (deprecated features removed IIRC). Hopefully an uncommon occurrence 🙂

**Comment by jthegedus** [comment]
If there were a plugin for this I would suggest it just supports awscli v2 as it has its deps bundled.

**Comment by MetricMike** [comment]
Added, requires Python 3.7.5+. Supports v1, v2, and a hypothetical v3 assuming aws/aws-cli doesn't change the build from source instructions.

Builds/installs to a virtualenv and hooks into asdf shims so that it doesn't touch the rest of your python installation or pip packages and continues working if you installed with a bare 3.9+ python setup but are in a 3.7 project.

If you install this with an ASDF-provided python and then remove that python, this will break, but I don't think that's a worthwhile edge case for this to look out for.

**Comment by jthegedus** [comment]
>If you install this with an ASDF-provided python and then remove that python, this will break
By break, do you mean the plugin's install method, the whole plugin or just the AWS CLI? 

I thought AWS CLI v2 had system specific binaries that bundle their own Python deps so no need to build from source or require a local Python, am I understanding this incorrectly?

**Comment by MetricMike** [comment]
By break, I mean that:
```bash
asdf install python 3.9.1
asdf install awscli 2.19.24
aws --version #works
asdf uninstall python 3.9.1
aws --version #complains that ~/.asdf/installs/python/3.9.1 no longer exists
```

v2 does have platform-specific releases, but they're "just" a folder with an embedded python. By supporting the platform-specific releases, this plugin would have to support 4+ (v2 mac/windows/linux, v1 python) different installation patterns. By building from source, I can support any platform that looks like linux and has bash/tar/curl/Python3.7.5+.

My specific use case for this plugin required switching between v1 and v2, so only supporting v2 releases wasn't an option.

**Comment by jthegedus** [comment]
>My specific use case for this plugin required switching between v1 and v2, so only supporting v2 releases wasn't an option.

I see.

Is there a way to build v2 and embed the python with it during build so changing Python versions only affects v1?

**Comment by MetricMike** [comment]
Probably!

I think in a future enhancement, I'll move v2 installs to the bundled releases. I very much agree that not having to require an external would be great, and make this more like an asdf plugin instead of a fancy pip package.

Unfortunately, I don't have a mac environment to work with, but I think I can exploit github actions to do some error-driven development there.

**Comment by jthegedus** [comment]
>I think in a future enhancement, I'll move v2 installs to the bundled releases.

:tada: Looking forward to this!

I have a mac device and can assist with testing, just pint me in your repo!
