### ISSUE TITLE
Unfortunately all mongodb plugins are broken.

### ISSUE THREAD

**Issue by cocoonkid** [asdf-vm/asdf-plugins#426]
Unfortunately all mongodb plugins are broken.

**Comment by jthegedus** [comment]
Can you open an issue with the actual plugin repo? We don't author it, just have a short-name association with the Git URL and name here.

Plugins can be installed via their Git URL as well with `asdf plugin add <name> <git url>` so if you find other implementations of the plugin you can install directly, by-passing this repo.

**Comment by itspngu** [comment]
Just bumped into this. I have a feeling this issue was about the mongosh and mongo-tools plugins, both of them broke in june and I didn't realize because you don't get notifications for failing CI when you're not watching a repo, even if it's your own /shrug

https://github.com/itspngu/asdf-mongo-tools/commit/deeb35556c4725b1881ab44b7181fa9a4151adb3
https://github.com/itspngu/asdf-mongosh/commit/83805139e912cd68f552f2f6d3ae802d29e772cd

If that's the case I think this could be closed. Sorry for the trouble @cocoonkid :)

If it's about the mongodb plugin (https://github.com/sylph01/asdf-mongodb), that one is the database itself and it's been broken for a long time. I considered forking and fixing it, but I don't have a use case for installing a database through asdf so I didn't :P

**Comment by cocoonkid** [comment]
@itspngu Thanks for updating this thread. Closing this thread!

It was indeed about  (https://github.com/sylph01/asdf-mongodb).

Your comment about the non-existing use case made me just run it via docker :)
Thank you for the mongo-tools ! loving it


@jthegedus   Thank you too!

**Comment by SuperSonicHub1** [comment]
@cocoonkid Think you forgot to close the issue.

**Comment by cocoonkid** [comment]
@SuperSonicHub1  thanks :-)
