### ISSUE TITLE
Remove asdf-desk plugin

### ISSUE THREAD

**Issue by marcwrobel** [asdf-vm/asdf-plugins#670]
### Is your feature request related to a problem? Please describe

The [asdf-desk](https://github.com/endorama/asdf-desk) repository has been archived by its author, @endorama. So it is safe to assume that this plugin is not maintained anymore.

### Describe the proposed solution

This plugin should be removed from the asdf-plugins repository.

### Describe similar `asdf` features and why they are not sufficient

N/A

### Describe other workarounds you've considered

This plugin could also be transferred to asdf-community.

**Comment by endorama** [comment]
👋 I've been not using `desk` for a while and stopped maintaining the repo too, but I forgot to remove it from the plugin list.

Happy to transfer this to asdf-community if there is interest in maintaining it, let me just check the status of the repo!

**Comment by endorama** [comment]
Had a look, I think the only thing needed is to port the CI to GiHub Actions (it still uses Travis).

**Comment by marcwrobel** [comment]
Thanks @endorama. @smorimoto, should we move this plugin to https://github.com/asdf-community or just remove it from the list ?

**Comment by jthegedus** [comment]
If it is no longer working, I think the best course is to remove it from the plugin list, it can be added again later once it is migrated owners or not.

**Comment by marcwrobel** [comment]
@jthegedus, I do not know if it's working or not, but @endorama seems to think it is still working.

Should we remove it from the plugin list for now and add it back if and when it has been migrated to ansible-community ?

**Comment by jthegedus** [comment]
If it is working then we should leave it here even if the repo is archived. The fact it is archived doesn't stop people using it nor does it imply it is not working. If it stops working at some point then we can remove it and add a new replacement repo once someone makes a replacement.

**Comment by marcwrobel** [comment]
Ok, thanks a lot for the clarification @jthegedus.

**Comment by jthegedus** [comment]
@marcwrobel I do realise that marking a repo as archived is an indicator from the author that no further improvements or fixes will be made. This is an important signal to pay attention to and is why we recommend people read the repos of each plugin they use. This repo is merely a convenience, not a sanctioned list. Again, I view it as a user-land responsibility, and I guess we (asdf core team) view it as such since we offer no explicit guarantees regarding the usage of this repo and in-fact discourage it's use. The maintenance of this repo is purely until we produce an alternative for remote plugin discovery in the core tool.
